NewsAndChannel/Models/ChannelViewModel.cs
using NewsAndChannel.Repository.Models;
using NewsAndChannel.Service.Generic;
using NewsAndChannel.Service.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NewsAndChannel.Models
{
    public class ChannelViewModel
    {
        public Channel channel { get; set; }
        public List<News> newsList { get; set; }

        public GeneralListingResponseModel<ChannelModel> responseModel { get; set; }

        public GeneralListingRequestModel requestModel { get; set; }


        public int totalPage { get; set; }

      
    }
}

NewsAndChannel/Models/NewsViewModel.cs
using NewsAndChannel.Repository.Models;
using NewsAndChannel.Service.Generic;
using NewsAndChannel.Service.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NewsAndChannel.Models
{
    public class NewsViewModel
    {

        public GeneralListingResponseModel<NewsModel> responseModel { get; set; }

        public GeneralListingRequestModel requestModel { get; set; }
        public News news { get; set; }
        public List<Channel> channelList { get; set; }      
        public int totalPage { get; set; }
             
    }
}

NewsAndChannel/Controllers/ChannelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewsAndChannel.Controllers
{
    public class ChannelController : Controller
    {
        // GET: Channel
        public ActionResult List()
        {
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
    }
}

NewsAndChannel/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewsAndChannel.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NewsAndChannel/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewsAndChannel.Controllers
{
    public class NewsController : Controller
    {
        public ActionResult List()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // GET: News/Create/
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

      
    }
}

NewsAndChannel/Views/Channel/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div ng-controller="CreateController as createCtrl" class="margin-top-80px">

    <div class="row" style="margin-top:5px">

        @*Links*@
        <div class="col-md-8">
            <span style="float:left">
                @Html.ActionLink("Channel List", "List", "Channel", null, null)
                >
                <span class="table-anchor">
                    Create Channel
                </span>
            </span>
        </div>


        <div class="col-md-4 text-right">
            <button type="button" class="btn ra-100 btn-blue btn-width-180" ng-click="createCtrl.Submit()">SAVE</button>
        </div>
    </div>

    @*Details*@
    <div class="row">

        <div class="col-lg-11">
            <div class="row">
                <div class="col-lg-3 h3-name">
                    Channel Info
                </div>
            </div>

            <hr />

            <div class="form-group">
                <div class="info-title-small-black">
                    Name
                </div>
                <div>
                    <input type="text" class="form-control info-title-small-black" placeholder="Channel Name"
                           ng-model="createCtrl.record.Name" style="max-width:780px" maxlength="256" />
                </div>
            </div>

            <div class="form-group">
                <div class="info-title-small-black">
                    Description
                </div>
                <div>
                    <textarea class="form-control info-title-small-black" placeholder="Description"
                              ng-model="createCtrl.record.Description" style="max-width:780px"></textarea>
                </div>
            </div>

            @*Multi-selection*@
            <div class="form-group">
                <div class="info-title-small-black">
                    Select multiple news
                </div>
                <div class="chosen-container chosen-container-multi" ng-class="createCtrl.showNewsList ? 'chosen-with-drop chosen-container-active' : ''" ng-click="createCtrl.openNewsList(); $event.stopPropagation()" style="max-width: 780px;" title="">
                    <ul class="chosen-choices">
                        <li class="search-choice" ng-repeat="rec in createCtrl.SelectedNewsList" ng-click="$event.stopPropagation()">
                            <span>{{rec.Title}}</span><i class="search-choice-close" ng-click="createCtrl.removeNews(rec); $event.stopPropagation()"></i>
                        </li>

                        <li class="search-field ms-hover" style="">
                            <input type="text" placeholder="{{createCtrl.SelectedNewsList.length > 0 ? 'Click or type to select...' : 'Click or type to select...' }}" ng-model="createCtrl.searchNews" ng-keyup="createCtrl.refreshNewsList()" ng-focus="createCtrl.refreshNewsList()" />
                        </li>
                    </ul>

                    <div class="chosen-drop" click-outside="createCtrl.hideAllList()">
                        <ul class="chosen-results">
                            <li class="active-result" ng-repeat="rec in createCtrl.NewsList" ng-click="createCtrl.updateNewsList(rec)" ng-hide="rec.selected">
                                <div>{{rec.Title}}</div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>


        </div>
    </div>

</div>


@section Scripts{
    <script src="~/Scripts/controllers/Channel/CreateController.js"></script>
}

NewsAndChannel/Views/Channel/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div ng-controller="EditController as editCtrl" class="margin-top-80px">

    <div class="row" style="margin-top:5px">

        @*Links*@
        <div class="col-md-8">
            <span style="float:left">
                @Html.ActionLink("Channel List", "List", "Channel", null, null)
                >
                <span class="table-anchor">
                    Edit Channel
                </span>
            </span>
        </div>


        <div class="col-md-4 text-right">
            <button type="button" class="btn ra-100 btn-blue btn-width-180" ng-click="editCtrl.Submit()">SAVE</button>
            <a href="javascript:void(0);" ng-click="editCtrl.Delete()" class=""> DELETE </a>
        </div>
    </div>

    @*Details*@
    <div class="row">

        <div class="col-lg-11">
            <div class="row">
                <div class="col-lg-3 h3-name">
                    Channel Info
                </div>
            </div>

            <hr />

            <div class="form-group">
                <div class="info-title-small-black">
                    Name
                </div>
                <div>
                    <input type="text" class="form-control info-title-small-black" placeholder="News Title"
                           ng-model="editCtrl.record.Name" style="max-width:780px" maxlength="256" />
                </div>
            </div>

            <div class="form-group">
                <div class="info-title-small-black">
                    Description
                </div>
                <div>
                    <textarea class="form-control info-title-small-black" placeholder="Content"
                              ng-model="editCtrl.record.Description" style="max-width:780px"></textarea>
                </div>
            </div>

            @*Multi-selection*@
            <div class="form-group">
                <div class="info-title-small-black">
                    Select multiple news
                </div>
                <div class="chosen-container chosen-container-multi" ng-class="editCtrl.showNewsList ? 'chosen-with-drop chosen-container-active' : ''" ng-click="editCtrl.openNewsList(); $event.stopPropagation()" style="max-width: 780px;" title="">
                    <ul class="chosen-choices">
                        <li class="search-choice" ng-repeat="rec in editCtrl.SelectedNewsList" ng-click="$event.stopPropagation()">
                            <span>{{rec.Title}}</span><i class="search-choice-close" ng-click="editCtrl.removeNews(rec); $event.stopPropagation()"></i>
                        </li>

                        <li class="search-field ms-hover" style="">
                            <input type="text" placeholder="{{editCtrl.SelectedNewsList.length > 0 ? 'Click or type to select...' : 'Click or type to select...' }}" ng-model="editCtrl.searchNews" ng-keyup="editCtrl.refreshNewsList()" ng-focus="editCtrl.refreshNewsList()" />
                        </li>
                    </ul>

                    <div class="chosen-drop" click-outside="editCtrl.hideAllList()">
                        <ul class="chosen-results">
                            <li class="active-result" ng-repeat="rec in editCtrl.NewsList" ng-click="editCtrl.updateNewsList(rec)" ng-hide="rec.selected">
                                <div>{{rec.Title}}</div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>


        </div>
    </div>

</div>


@section Scripts{
    <script src="~/Scripts/controllers/Channel/EditController.js"></script>
}

NewsAndChannel/Views/Channel/List.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div ng-controller="ListController as listCtrl" class="margin-top-80px">

    @*Filter*@
    <div class="row margin-top-15px">
        <div class="col-md-11" style="padding-left:0px">
            <div class="input-group">
                <input type="text"
                       class="form-control"
                       placeholder="Search Title" ng-model="listCtrl.searchKeyword" ng-keyup="listCtrl.search($event)"
                       style="width: 100%;float: none;" />
            </div>
        </div>

        <div class="col-md-1">
            <div class="input-group">
                <a class="fc-button" href="/Channel/Create">Create </a>
            </div>
        </div>
    </div>

    @*Table List*@
    <div class="row margin-top-15px">
        <div>
            <table class="table table-bordered table-hover ">
                <thead>
                    <tr class="vertical-align-middle">
                        <th ng-repeat="column in listCtrl.tableColumn">
                            <div ng-click="listCtrl.sort(column.EnableSorting, column.SortingField)">
                                {{column.Name}}
                                <span><i class="pull-right glyph-icon" ng-class="listCtrl.sortIcon(column.EnableSorting, column.SortingField)"></i></span>
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody ng-if="listCtrl.List.length > 0">
                    <tr class="vertical-align-middle" ng-repeat="record in listCtrl.List">
                        <td class="text-center">{{$index + 1 + ((listCtrl.page-1) * listCtrl.pageSize)}}.</td>
                        <td>
                            <div style="width:150px;word-wrap:break-word;">
                                {{record.Name}}
                            </div>
                        </td>
                        <td style="width:100px">{{record.Description}}</td>
                        <td>
                            {{record.CreatedDate | amUtc | amLocal | amDateFormat:'DD-MM-YYYY'}}<br />
                            {{record.CreatedDate | amUtc | amLocal | amDateFormat:'h:mm a'}}
                            @*{{record.CreatedDate}}*@
                        </td>
                        <td>
                            {{record.UpdatedDate | amUtc | amLocal | amDateFormat:'DD-MM-YYYY'}}<br />
                            {{record.UpdatedDate | amUtc | amLocal | amDateFormat:'h:mm a'}}
                            @*{{record.UpdatedDate}}*@
                        </td>
                        <td>
                            <a ng-click="listCtrl.remove(record)">
                                Delete
                            </a>
                            |
                            <a href="Channel/Edit/{{record.ID}}">
                                Edit
                            </a>
                        </td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td colspan="9" class="text-center" ng-if="listCtrl.List.length < 1">
                            No records
                        </td>
                    </tr>
                </tbody>
            </table>

            @*Paging*@
            <div class="row" style="padding-top:20px;">

                <div class="pull-right">
                    <ul uib-pagination
                        total-items="listCtrl.totalCount"
                        items-per-page="listCtrl.pageSize"
                        ng-change="listCtrl.refreshList()"
                        ng-model="listCtrl.page"
                        max-size="3"
                        class="pagination-sm"
                        boundary-link-numbers="true"></ul>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Scripts/controllers/Channel/ListController.js"></script>
}

NewsAndChannel/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NewsAndChannel/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NewsAndChannel/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NewsAndChannel/Views/News/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div ng-controller="CreateController as createCtrl" class="margin-top-80px">

    <div class="row" style="margin-top:5px">

        @*Links*@
        <div class="col-md-8">
            <span style="float:left">
                @Html.ActionLink("News List", "List", "News", null, null)
                >
                <span class="table-anchor">
                    Create News
                </span>
            </span>
        </div>


        <div class="col-md-4 text-right">
            <button type="button" class="btn ra-100 btn-blue btn-width-180" ng-click="createCtrl.Submit()">SAVE</button>
        </div>
    </div>

    @*Details*@
    <div class="row">

        <div class="col-lg-11">
            <div class="row">
                <div class="col-lg-3 h3-name">
                    News Info
                </div>
            </div>

            <hr />

            <div class="form-group">
                <div class="info-title-small-black">
                    Title
                </div>
                <div>
                    <input type="text" class="form-control info-title-small-black" placeholder="News Title"
                           ng-model="createCtrl.record.Title" style="max-width:780px" maxlength="256" />
                </div>
            </div>

            <div class="form-group">
                <div class="info-title-small-black">
                    Content
                </div>
                <div>
                    <textarea class="form-control info-title-small-black" placeholder="Content"
                              ng-model="createCtrl.record.Content" style="max-width:780px"></textarea>
                </div>
            </div>

            @*Multi-selection*@
            <div class="form-group">
                <div class="info-title-small-black">
                    Select multiple channels
                </div>
                <div class="chosen-container chosen-container-multi" ng-class="createCtrl.showChannelList ? 'chosen-with-drop chosen-container-active' : ''" ng-click="createCtrl.openChannelList(); $event.stopPropagation()" style="max-width: 780px;" title="">
                    <ul class="chosen-choices">
                        <li class="search-choice" ng-repeat="rec in createCtrl.SelectedChannelList" ng-click="$event.stopPropagation()">
                            <span>{{rec.Name}}</span><i class="search-choice-close" ng-click="createCtrl.removeChannel(rec); $event.stopPropagation()"></i>
                        </li>

                        <li class="search-field ms-hover" style="">
                            <input type="text" placeholder="{{createCtrl.SelectedChannelList.length > 0 ? 'Click or type to select...' : 'Click or type to select...' }}" ng-model="createCtrl.searchChannel" ng-keyup="createCtrl.refreshChannelList()" ng-focus="createCtrl.refreshChannelList()" />
                        </li>
                    </ul>

                    <div class="chosen-drop" click-outside="createCtrl.hideAllList()">
                        <ul class="chosen-results">
                            <li class="active-result" ng-repeat="rec in createCtrl.ChannelList" ng-click="createCtrl.updateChannelList(rec)" ng-hide="rec.selected">
                                <div>{{rec.Name}}</div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>


        </div>
    </div>

</div>


@section Scripts{
    <script src="~/Scripts/controllers/News/CreateController.js"></script>
}

NewsAndChannel/Views/News/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div ng-controller="EditController as editCtrl" class="margin-top-80px">

    <div class="row" style="margin-top:5px">

        @*Links*@
        <div class="col-md-8">
            <span style="float:left">
                @Html.ActionLink("News List", "List", "News", null, null)
                >
                <span class="table-anchor">
                    Edit News
                </span>
            </span>
        </div>


        <div class="col-md-4 text-right">
            <button type="button" class="btn ra-100 btn-blue btn-width-180" ng-click="editCtrl.Submit()">SAVE</button>
            <a href="javascript:void(0);" ng-click="editCtrl.Delete()" class=""> DELETE </a>
        </div>
    </div>

    @*Details*@
    <div class="row">

        <div class="col-lg-11">
            <div class="row">
                <div class="col-lg-3 h3-name">
                    News Info
                </div>
            </div>

            <hr />

            <div class="form-group">
                <div class="info-title-small-black">
                    Title
                </div>
                <div>
                    <input type="text" class="form-control info-title-small-black" placeholder="News Title"
                           ng-model="editCtrl.record.Title" style="max-width:780px" maxlength="256" />
                </div>
            </div>

            <div class="form-group">
                <div class="info-title-small-black">
                    Content
                </div>
                <div>
                    <textarea class="form-control info-title-small-black" placeholder="Content"
                              ng-model="editCtrl.record.Content" style="max-width:780px"></textarea>
                </div>
            </div>

            @*Multi-selection*@
            <div class="form-group">
                <div class="info-title-small-black">
                    Select multiple channels
                </div>
                <div class="chosen-container chosen-container-multi" ng-class="editCtrl.showChannelList ? 'chosen-with-drop chosen-container-active' : ''" ng-click="editCtrl.openChannelList(); $event.stopPropagation()" style="max-width: 780px;" title="">
                    <ul class="chosen-choices">
                        <li class="search-choice" ng-repeat="rec in editCtrl.SelectedChannelList" ng-click="$event.stopPropagation()">
                            <span>{{rec.Name}}</span><i class="search-choice-close" ng-click="editCtrl.removeChannel(rec); $event.stopPropagation()"></i>
                        </li>
                        
        <li class="search-field ms-hover" style="">
            <input type="text" placeholder="{{editCtrl.SelectedChannelList.length > 0 ? 'Click or type to select...' : 'Click or type to select...' }}" ng-model="editCtrl.searchChannel" ng-keyup="editCtrl.refreshChannelList()" ng-focus="editCtrl.refreshChannelList()" />
        </li>
                    </ul>

                    <div class="chosen-drop" click-outside="editCtrl.hideAllList()">
                        <ul class="chosen-results">
                            <li class="active-result" ng-repeat="rec in editCtrl.ChannelList" ng-click="editCtrl.updateChannelList(rec)" ng-hide="rec.selected">
                                <div>{{rec.Name}}</div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>


        </div>
    </div>

</div>


@section Scripts{
    <script src="~/Scripts/controllers/News/EditController.js"></script>
}

NewsAndChannel/Views/News/List.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div ng-controller="ListController as listCtrl" class="margin-top-80px">
    @*Filter*@
    <div class="row margin-top-15px">
        <div class="col-md-11" style="padding-left:0px">
            <div class="input-group">
                <input type="text"
                       class="form-control"
                       placeholder="Search Title" ng-model="listCtrl.searchKeyword" ng-keyup="listCtrl.search($event)"
                       style="width: 100%;float: none;" />
            </div>
        </div>

        <div class="col-md-1">
            <div class="input-group">
                <a class="fc-button" href="/News/Create">Create </a>
            </div>
        </div>
    </div>

    @*Table List*@
    <div class="row margin-top-15px">
        <div>
            <table class="table table-bordered table-hover ">
                <thead>
                    <tr class="vertical-align-middle">
                        <th ng-repeat="column in listCtrl.tableColumn">
                            <div ng-click="listCtrl.sort(column.EnableSorting, column.SortingField)">
                                {{column.Name}}
                                <span><i class="pull-right glyph-icon" ng-class="listCtrl.sortIcon(column.EnableSorting, column.SortingField)"></i></span>
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody ng-if="listCtrl.List.length > 0">
                    <tr class="vertical-align-middle" ng-repeat="record in listCtrl.List">
                        <td class="text-center">{{$index + 1 + ((listCtrl.page-1) * listCtrl.pageSize)}}.</td>
                        <td>
                            <div style="width:150px;word-wrap:break-word;">
                                {{record.Title}}
                            </div>
                        </td>
                        <td style="width:100px">{{record.Content}}</td>
                        <td>
                            {{record.CreatedDate | amUtc | amLocal | amDateFormat:'DD-MM-YYYY'}}<br />
                            {{record.CreatedDate | amUtc | amLocal | amDateFormat:'h:mm a'}}
                            @*{{record.CreatedDate}}*@
                        </td>
                        <td>
                            {{record.UpdatedDate | amUtc | amLocal | amDateFormat:'DD-MM-YYYY'}}<br />
                            {{record.UpdatedDate | amUtc | amLocal | amDateFormat:'h:mm a'}}
                            @*{{record.UpdatedDate}}*@
                        </td>
                        <td>
                            <a ng-click="listCtrl.remove(record)">
                                Delete
                            </a>
                            |
                            <a href="News/Edit/{{record.ID}}">
                                Edit
                            </a>
                        </td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td colspan="9" class="text-center" ng-if="listCtrl.List.length < 1">
                            No records
                        </td>
                    </tr>
                </tbody>
            </table>

            @*Paging*@
            <div class="row" style="padding-top:20px;">

                <div class="pull-right">
                    <ul uib-pagination
                        total-items="listCtrl.totalCount"
                        items-per-page="listCtrl.pageSize"
                        ng-change="listCtrl.refreshList()"
                        ng-model="listCtrl.page"
                        max-size="3"
                        class="pagination-sm"
                        boundary-link-numbers="true"></ul>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Scripts/controllers/News/ListController.js"></script>
}

NewsAndChannel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html  ng-app="myApp" ng-controller="MainController as mainCtrl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/angular-ui/ui-bootstrap-tpls.min.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/angular-moment.js"></script>
    <script src="~/Scripts/controllers/app.js"></script>
    <script src="~/Scripts/controllers/main.js"></script>
    <script src="~/Scripts/factory/serverCall.js"></script>
    <link href="~/Content/Loader.css" rel="stylesheet" /> @*For Loading Icon*@
    <link href="~/Content/Custom.css" rel="stylesheet" />
    <link href="~/Content/admin-style.css" rel="stylesheet" />
</head>
<body>
    @*For Loading Icon*@
    <div class="loader-float" ng-show="mainCtrl.Page.getLoader()">
        <div class="cssload-loader-inner">
            <div class="cssload-cssload-loader-line-wrap-wrap" style="border-color: transparent !important;">
                <div class="cssload-loader-line-wrap" style="border-color: transparent !important;"></div>
            </div>
            <div class="cssload-cssload-loader-line-wrap-wrap" style="border-color: transparent !important;">
                <div class="cssload-loader-line-wrap" style="border-color: transparent !important;"></div>
            </div>
            <div class="cssload-cssload-loader-line-wrap-wrap" style="border-color: transparent !important;">
                <div class="cssload-loader-line-wrap" style="border-color: transparent !important;"></div>
            </div>
            <div class="cssload-cssload-loader-line-wrap-wrap">
                <div class="cssload-loader-line-wrap" style="border-color: #408530 !important;"></div>
            </div>
            <div class="cssload-cssload-loader-line-wrap-wrap">
                <div class="cssload-loader-line-wrap" style="border-color: transparent !important;"></div>
            </div>
        </div>
    </div>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("News", "List", "News")</li>
                    <li>@Html.ActionLink("Channel", "List", "Channel")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*<script src="~/Scripts/admin-style.js"></script>*@
    @RenderSection("scripts", required: false)
</body>
</html>